# Generated by Django 6.0.2 on 2026-03-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
    ]
