# Generated by Django 6.0.2 on 2026-03-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeprofile',
            name='grade',
            field=models.CharField(choices=[('INTRO', 'Intro'), ('GRADE_3', 'Grade 3'), ('GRADE_2', 'Grade 2'), ('GRADE_1', 'Grade 1'), ('FIBA', 'Fiba')], default='TRAINEE', max_length=20),
        ),
    ]
