# Generated by Django 6.0.2 on 2026-03-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_refereeprofile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refereeprofile',
            name='referee_number',
        ),
    ]
