# Generated by Django 6.0.2 on 2026-03-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_refereeprofile_referee_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refereeavailability',
            options={'ordering': ['day_of_week', 'start_time'], 'verbose_name_plural': 'Referee availabilities'},
        ),
        migrations.RemoveField(
            model_name='refereeavailability',
            name='date',
        ),
        migrations.AddField(
            model_name='refereeavailability',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='SAT', max_length=3),
        ),
    ]
