# Generated by Django 6.0.2 on 2026-03-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_refereeavailability_day_of_week'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='refereeavailability',
            constraint=models.UniqueConstraint(fields=('referee', 'day_of_week'), name='unique_referee_availability'),
        ),
    ]
