# Generated by Django 6.0.3 on 2026-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_refereeavailability_unique_referee_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refereeprofile',
            name='grade',
            field=models.CharField(choices=[('INTRO', 'Intro'), ('GRADE_3', 'Grade 3'), ('GRADE_2', 'Grade 2'), ('GRADE_1', 'Grade 1'), ('FIBA', 'Fiba')], default='INTRO', max_length=20),
        ),
    ]
