# Generated by Django 6.0.3 on 2026-03-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_refereeprofile_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='home_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
