# Generated by Django 6.0.3 on 2026-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_home_address_user_home_lat_user_home_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("REFEREE", "Referee"),
                    ("CLUB_MANAGER", "Club Manager"),
                    ("SCHOOL_MANAGER", "School Manager"),
                    ("COLLEGE_MANAGER", "College Manager"),
                    ("DOA", "DOA"),
                    ("NL", "National League"),
                ],
                default="REFEREE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="bipin_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="doa_approved",
            field=models.BooleanField(default=False),
        ),
    ]
