# Generated by Django 6.0.3 on 2026-03-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("users", "0009_user_account_type_and_approval_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_team_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="managed_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="clubs.team",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="manager_scope",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("CLUB", "Club"),
                    ("SCHOOL", "School"),
                    ("COLLEGE", "College"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
