# Generated by Django 6.0.3 on 2026-03-30 17:44

from django.db import migrations, models


def map_legacy_account_types(apps, schema_editor):
    User = apps.get_model("users", "User")

    legacy_to_new = {
        "CLUB_MANAGER": "CLUB",
        "SCHOOL_MANAGER": "SCHOOL",
        "COLLEGE_MANAGER": "COLLEGE",
    }

    for legacy_value, new_value in legacy_to_new.items():
        User.objects.filter(account_type=legacy_value).update(account_type=new_value)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_team_manager_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_head_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_id_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('REFEREE', 'Referee'), ('CLUB', 'Club'), ('SCHOOL', 'School'), ('COLLEGE', 'College'), ('DOA', 'DOA'), ('NL', 'National League')], default='REFEREE', max_length=30),
        ),
        migrations.RunPython(map_legacy_account_types, noop_reverse),
    ]
