# Generated by Django 6.0.3 on 2026-03-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_institution_head_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_id_photo',
            field=models.FileField(blank=True, null=True, upload_to='verification_ids/'),
        ),
    ]
