# Generated by Django 6.0.3 on 2026-04-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_cleanup_non_referee_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeprofile',
            name='appointed_availability_effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refereeprofile',
            name='appointed_availability_pending',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
