# Generated by Django 6.0.2 on 2026-03-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('fee_per_game', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_information', models.TextField(blank=True, default='')),
                ('referees_required', models.PositiveIntegerField(default=0)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='venues.venue')),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['start_date'],
            },
        ),
    ]
