# Generated by Django 6.0.3 on 2026-03-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0007_alter_refereeprofile_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignments', to='events.event')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='users.refereeprofile')),
            ],
            options={
                'db_table': 'events_event_referee_assignment',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'referee'), name='unique_event_referee_assignment')],
            },
        ),
    ]
