# Generated by Django 6.0.3 on 2026-03-30 17:44

from django.db import migrations, models


def populate_event_type(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    account_type_to_event_type = {
        "CLUB": "CLUB",
        "SCHOOL": "SCHOOL",
        "COLLEGE": "COLLEGE",
        "CLUB_MANAGER": "CLUB",
        "SCHOOL_MANAGER": "SCHOOL",
        "COLLEGE_MANAGER": "COLLEGE",
    }

    for event in Event.objects.select_related("created_by").all():
        created_by = getattr(event, "created_by", None)
        if not created_by:
            continue

        mapped_type = account_type_to_event_type.get(created_by.account_type)
        if mapped_type and event.event_type != mapped_type:
            event.event_type = mapped_type
            event.save(update_fields=["event_type"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CLUB', 'Club'), ('SCHOOL', 'School'), ('COLLEGE', 'College')], default='CLUB', max_length=20),
        ),
        migrations.RunPython(populate_event_type, noop_reverse),
    ]
