# Generated by Django 6.0.3 on 2026-03-25 16:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0008_refereeassignment_public_transport_fare_and_more'),
        ('users', '0008_user_home_address_user_home_lat_user_home_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_mode', models.CharField(choices=[('MILEAGE', 'Mileage'), ('PUBLIC_TRANSPORT', 'Public Transport')], default='MILEAGE', max_length=20)),
                ('travel_source', models.CharField(choices=[('MILEAGE', 'Mileage'), ('PUBLIC_TRANSPORT', 'Public Transport'), ('BACK_TO_BACK_SAME_VENUE', 'Back-to-back same venue')], default='MILEAGE', max_length=40)),
                ('mileage_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('public_transport_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_back_to_back_same_venue', models.BooleanField(default=False)),
                ('missing_distance_data', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_record', to='games.refereeassignment')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='games.game')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_records', to='users.refereeprofile')),
            ],
            options={
                'db_table': 'expenses_expense_record',
                'ordering': ['game__date', 'game__time', 'assignment__id'],
            },
        ),
    ]
