# Generated by Django 6.0.3 on 2026-04-12 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('users', '0014_refereeprofile_appointed_availability_effective_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEarningsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('games_count', models.PositiveIntegerField(default=0)),
                ('base_fee_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('travel_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mileage_km_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('missing_distance_games', models.PositiveIntegerField(default=0)),
                ('items_snapshot', models.JSONField(blank=True, default=list)),
                ('finalized_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_earnings_snapshots', to='users.refereeprofile')),
            ],
            options={
                'db_table': 'expenses_monthly_earnings_snapshot',
                'ordering': ['-year', '-month', 'game_type'],
                'constraints': [models.UniqueConstraint(fields=('referee', 'game_type', 'year', 'month'), name='unique_monthly_earnings_snapshot_per_ref_type'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='expenses_monthly_snapshot_month_range')],
            },
        ),
    ]
