# Generated by Django 6.0.3 on 2026-04-15 23:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_monthlyearningssnapshot'),
        ('users', '0014_refereeprofile_appointed_availability_effective_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaymentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('games_count', models.PositiveIntegerField(default=0)),
                ('total_claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_payments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payment_approvals', to='users.refereeprofile')),
            ],
            options={
                'db_table': 'expenses_monthly_payment_approval',
                'ordering': ['-year', '-month', '-confirmed_at'],
                'constraints': [models.UniqueConstraint(fields=('referee', 'game_type', 'year', 'month'), name='unique_monthly_payment_approval_per_ref_type'), models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='expenses_payment_approval_month_range')],
            },
        ),
    ]
