# Generated by Django 6.0.2 on 2026-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('CLUB', 'Club'), ('SCHOOL', 'School')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING_COVER', 'Pending Cover'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING_COVER', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('custom_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cover_requests_cover_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
