# Generated by Django 6.0.2 on 2026-03-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cover_requests', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coverrequest',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests', to='games.game'),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='referee_slot',
            field=models.ForeignKey(blank=True, help_text='The assignment being replaced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_requests', to='games.refereeassignment'),
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
