# Generated by Django 6.0.2 on 2026-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0002_initial'),
        ('users', '0006_refereeavailability_unique_referee_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverrequest',
            name='replacement_referee',
            field=models.ForeignKey(blank=True, help_text='The referee covering the game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_assignments', to='users.refereeprofile'),
        ),
    ]
