# Generated by Django 6.0.2 on 2026-03-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0003_coverrequest_replacement_referee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverrequest',
            old_name='replacement_referee',
            new_name='replaced_by',
        ),
    ]
