# Generated by Django 6.0.2 on 2026-03-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0004_rename_replacement_referee_coverrequest_replaced_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverrequest',
            name='request_type',
            field=models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('CLUB', 'Club'), ('SCHOOL', 'School'), ('FRIENDLY', 'Friendly')], max_length=20),
        ),
    ]
