# Generated by Django 6.0.2 on 2026-03-11 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0005_alter_coverrequest_request_type'),
        ('games', '0003_alter_game_game_type_game_home_away_different'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverrequest',
            name='referee_slot',
            field=models.ForeignKey(help_text='The assignment being replaced (required - cover requests need an existing referee to replace)', on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests', to='games.refereeassignment'),
        ),
    ]
