# Generated by Django 6.0.3 on 2026-03-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0006_alter_coverrequest_referee_slot'),
        ('games', '0004_nonappointedslot_alter_refereeassignment_options_and_more'),
        ('users', '0006_refereeavailability_unique_referee_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverrequest',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='coverrequest',
            name='referee_slot',
            field=models.ForeignKey(help_text='The assignment being replaced.', on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests', to='games.refereeassignment'),
        ),
        migrations.AlterField(
            model_name='coverrequest',
            name='replaced_by',
            field=models.ForeignKey(blank=True, help_text='The referee covering the game.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_assignments', to='users.refereeprofile'),
        ),
    ]
