# Generated by Django 6.0.3 on 2026-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0007_remove_coverrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
