# Generated by Django 6.0.3 on 2026-03-20 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover_requests', '0008_alter_coverrequest_status'),
        ('users', '0007_alter_refereeprofile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverrequest',
            name='custom_fee',
        ),
        migrations.AddField(
            model_name='coverrequest',
            name='original_referee',
            field=models.ForeignKey(blank=True, help_text='The originally assigned referee at the time the cover request was created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_cover_requests', to='users.refereeprofile'),
        ),
    ]
