# Generated by Django 6.0.3 on 2026-03-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0008_refereeassignment_public_transport_fare_and_more"),
        ("users", "0008_user_home_address_user_home_lat_user_home_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_no", models.CharField(blank=True, default="", max_length=100)),
                ("incident_time", models.TimeField(blank=True, null=True)),
                (
                    "people_involved_no_1",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "people_involved_name_1",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                (
                    "people_involved_no_2",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "people_involved_name_2",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                ("people_involved_other", models.TextField(blank=True, default="")),
                ("incident_details", models.TextField()),
                ("action_taken", models.TextField()),
                ("signed_by", models.CharField(blank=True, default="", max_length=200)),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REVIEWED", "Reviewed"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="games.game",
                    ),
                ),
                (
                    "referee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_reports",
                        to="users.refereeprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to="users.user",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_submitted",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "reports_game_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="gamereport",
            constraint=models.UniqueConstraint(
                fields=("game", "referee"),
                name="unique_report_per_referee_per_game",
            ),
        ),
    ]
