# Generated by Django 6.0.3 on 2026-03-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='requires_appointed_referees',
            field=models.BooleanField(default=False),
        ),
    ]
