# Generated by Django 6.0.3 on 2026-04-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_division_requires_appointed_referees'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('competition_scope', models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('BOTH', 'Shared (DOA + NL)')], default='BOTH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clubs_age_group',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='competition_scope',
            field=models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('BOTH', 'Shared (DOA + NL)')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='division',
            name='age_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='clubs.agegroup'),
        ),
    ]
