# Generated by Django 6.0.3 on 2026-04-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_agegroup_division_competition_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='age_group',
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
    ]
