# Generated by Django 6.0.3 on 2026-04-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_division_age_group_delete_agegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='competition_scope',
        ),
    ]
