# Generated by Django 6.0.3 on 2026-04-13 16:43

from django.db import migrations, models


def convert_mixed_to_m(apps, schema_editor):
    Division = apps.get_model("clubs", "Division")
    Division.objects.filter(gender="MIXED").update(gender="M")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_division_competition_scope'),
    ]

    operations = [
        migrations.RunPython(convert_mixed_to_m, noop_reverse),
        migrations.AlterField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
