# Generated by Django 6.0.2 on 2026-03-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('SCHOOL', 'School'), ('CLUB', 'Club')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_games', to='clubs.team')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='clubs.division')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_games', to='clubs.team')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='venues.venue')),
            ],
            options={
                'db_table': 'games_game',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='RefereeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREW_CHIEF', 'Crew Chief'), ('UMPIRE_1', 'Umpire 1'), ('UMPIRE_2', 'Umpire 2')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_assignments', to='games.game')),
            ],
            options={
                'db_table': 'games_referee_assignment',
            },
        ),
    ]
