# Generated by Django 6.0.2 on 2026-03-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeassignment',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_assignments', to='users.refereeprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='refereeassignment',
            unique_together={('game', 'role')},
        ),
    ]
