# Generated by Django 6.0.2 on 2026-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('games', '0002_initial'),
        ('venues', '0002_alter_venue_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('SCHOOL', 'School'), ('CLUB', 'Club'), ('FRIENDLY', 'Friendly')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='home_away_different'),
        ),
    ]
