# Generated by Django 5.2.7 on 2025-11-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_competition_team_alter_game_competition_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='crew_chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_crew_chief', to='users.refereeprofile'),
        ),
        migrations.AddField(
            model_name='game',
            name='umpire1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_umpire1', to='users.refereeprofile'),
        ),
        migrations.AddField(
            model_name='game',
            name='umpire2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_umpire2', to='users.refereeprofile'),
        ),
        migrations.DeleteModel(
            name='GameAssignment',
        ),
    ]
