# Generated by Django 6.0.3 on 2026-03-14 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('games', '0003_alter_game_game_type_game_home_away_different'),
        ('users', '0006_refereeavailability_unique_referee_availability'),
        ('venues', '0002_alter_venue_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAppointedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREW_CHIEF', 'Crew Chief'), ('UMPIRE_1', 'Umpire 1')], max_length=20)),
                ('source_type', models.CharField(choices=[('CLUB', 'Club'), ('SCHOOL', 'School')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['game__date', 'game__time', 'role'],
            },
        ),
        migrations.AlterModelOptions(
            name='refereeassignment',
            options={'ordering': ['game__date', 'game__time', 'role']},
        ),
        migrations.RemoveConstraint(
            model_name='game',
            name='home_away_different',
        ),
        migrations.AlterUniqueTogether(
            name='refereeassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='original_post_text',
            field=models.TextField(blank=True, default='', help_text='Original WhatsApp-style message used to create the game.'),
        ),
        migrations.AddField(
            model_name='game',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('REVOLUT', 'Revolut'), ('CLAIM', 'Claim')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_ASSIGNED', 'Partially Assigned'), ('FULLY_ASSIGNED', 'Fully Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=25),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('NON_APPOINTED', 'Non-Appointed'), ('FRIENDLY', 'Friendly')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='games_home_away_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='refereeassignment',
            constraint=models.UniqueConstraint(fields=('game', 'role'), name='unique_assignment_role_per_game'),
        ),
        migrations.AlterModelTable(
            name='game',
            table=None,
        ),
        migrations.AlterModelTable(
            name='refereeassignment',
            table=None,
        ),
        migrations.AddField(
            model_name='nonappointedslot',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_appointed_slots_claimed', to='users.refereeprofile'),
        ),
        migrations.AddField(
            model_name='nonappointedslot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_appointed_slots', to='games.game'),
        ),
        migrations.AddField(
            model_name='nonappointedslot',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_appointed_slots_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='nonappointedslot',
            constraint=models.UniqueConstraint(fields=('game', 'role'), name='unique_non_appointed_slot_role_per_game'),
        ),
    ]
