# Generated by Django 5.2.7 on 2025-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_crew_chief_game_umpire1_game_umpire2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='can_ref_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
