# Generated by Django 5.2.7 on 2025-11-27 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_competition_can_ref_cancel'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='referees_required',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.event')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.refereeprofile')),
            ],
            options={
                'unique_together': {('event', 'referee')},
            },
        ),
    ]
