# Generated by Django 6.0.3 on 2026-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_nonappointedslot_alter_refereeassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('CLUB', 'Club'), ('SCHOOLSchool', 'School'), ('COLLEGECollege', 'College'), ('FRIENDLY', 'Friendly')], max_length=20),
        ),
    ]
