# Generated by Django 5.2.7 on 2025-11-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_event_referees_required_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlist', 'Waitlist')], default='confirmed', max_length=20),
        ),
    ]
