# Generated by Django 6.0.3 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('DOA', 'DOA'), ('NL', 'National League'), ('CLUB', 'Club'), ('SCHOOL', 'School'), ('COLLEGE', 'College'), ('FRIENDLY', 'Friendly')], max_length=20),
        ),
    ]
