# Generated by Django 6.0.3 on 2026-03-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_game_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonappointedslot',
            name='source_type',
        ),
    ]
