# Generated by Django 5.2.7 on 2025-11-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_eventparticipation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='can_ref_cancel',
        ),
        migrations.AddField(
            model_name='gamecategory',
            name='can_ref_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
