# Generated by Django 6.0.3 on 2026-03-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_nonappointedslot_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refereeassignment',
            name='public_transport_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='refereeassignment',
            name='travel_mode',
            field=models.CharField(choices=[('MILEAGE', 'Mileage'), ('PUBLIC_TRANSPORT', 'Public Transport')], default='MILEAGE', max_length=20),
        ),
    ]
