# Generated by Django 6.0.3 on 2026-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_refereeassignment_public_transport_fare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='original_post_text',
        ),
    ]
