# Generated by Django 6.0.3 on 2026-04-12 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('COVER_REQUEST_STATUS', 'Cover Request Status'), ('GAME_REMINDER', 'Game Reminder'), ('EVENT_REMINDER', 'Event Reminder'), ('GAME_ASSIGNMENT_ACTIVITY', 'Game Assignment Activity'), ('EVENT_ASSIGNMENT_ACTIVITY', 'Event Assignment Activity'), ('ACCOUNT_APPROVAL', 'Account Approval'), ('COVER_REQUEST_ADMIN', 'Cover Request (Admin)'), ('REPORT_ADMIN', 'Report (Admin)')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('link_path', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, help_text='Optional unique key to avoid duplicate notifications.', max_length=180, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_user_notification',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe_per_user')],
            },
        ),
    ]
