# Generated by Django 6.0.3 on 2026-04-11 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('NON_APPOINTED_SLOT', 'Non-Appointed Slot'), ('COVER_REQUEST', 'Cover Request'), ('EVENT', 'Event')], max_length=30)),
                ('opportunity_id', models.PositiveBigIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations_snapshot',
                'ordering': ['-score', '-computed_at'],
                'indexes': [models.Index(fields=['user', '-score'], name='recommendation_user_score_idx'), models.Index(fields=['computed_at'], name='recommendation_computed_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity_type', 'opportunity_id'), name='unique_user_recommendation_snapshot')],
            },
        ),
    ]
